if ("${CMAKE_SIZEOF_VOID_P}" EQUAL "4")
  message(FATAL_ERROR "32-bit compilation is not supported")
else()
  if (CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64.*|AARCH64.*|arm64.*|ARM64.*)")
    set(REPERTORY_UNIX_ARCH armv8-a)
    set(IS_ARM64 TRUE)
  else()
    set(REPERTORY_UNIX_ARCH x86-64)
  endif()
endif()
