option(REPERTORY_ENABLE_TESTING "Enable testing" ON)

option(REPERTORY_ENABLE_S3 "Enable S3 mount support" OFF)
if (REPERTORY_ENABLE_S3)
  set(REPERTORY_DEFINITIONS ${REPERTORY_DEFINITIONS} -DREPERTORY_ENABLE_S3)

  option(REPERTORY_ENABLE_S3_TESTING "Enable S3 unit tests" OFF)
  if (REPERTORY_ENABLE_S3_TESTING)
    set(REPERTORY_DEFINITIONS ${REPERTORY_DEFINITIONS} -DREPERTORY_ENABLE_S3_TESTING)
  endif ()
endif()
